### PR TITLE
reset webview on returning to main activity

### PR DESCRIPTION
**Pull request by ripply**
this fixes an issue with videos continuing to play when returning to the main activity

### CODE REVIEW

**Comment by burntcookie90** [comment]
Didn't realize this was a bug, thanks for finding it!

Can't this be done by calling `mWebView.destroy()` in the `onDestroy()` or the `onDetach()`?

**Comment by ripply** [comment]
I'm not sure, I am still new to android, fix it however you feel is best, that does sound like it would be better.
I did notice after using the app more this does not fix the issue when sliding the activity to the right.

**Comment by ripply** [comment]
You were correct, it is now just one line to fix the issue, thanks for pointing me in the right direction.
Doing it that way also works when swiping away the activity.

**Comment by burntcookie90** [comment]
Thanks for the contirbution, is there a name you'd like me to mention on the "What's New" section when this gets released?

**Comment by ripply** [comment]
You don't have to put anything in the what's new section mentioning me, if you really want to then my github name is fine: ripply

**Comment by burntcookie90** [comment]
Sounds good!

**Pull request merged**
